version: '2'

services:

  item-app:
    image: ghcr.io/alan99abdullah/item-app:v1
    ports:
      - "80:8080"  
    depends_on:
      - item-db  
    restart: always  

  # Service for the item-db database
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db  
volumes:
  app-db:  
